### ISSUE TITLE
被B站裁员后，我思考了那些

### ISSUE THREAD

**Issue by xuya227939** [xuya227939/blog#148]
## 传送门

[5年经验(专升本)入职B站分享](https://juejin.cn/post/7076676933697667085)

### 前言

> 时光流逝，没想到已经一年多了，很久很久未在技术社区更新过文章，惭愧。也终于有勇气写个流水账了。在过去的一年中，也在不断的思考，自己将来（35岁后）能做什么？乃至于我在失业期间，也想过是否要留学？考研？（毕竟还年轻，本人97年）甚至是说专门待业1-2年，学习英语 run 到外企，再通过外企 remove 国外？一直认为国内35岁以后，还在一线开发，不现实。理由如下：

1. 精力比不上年轻人
2. 刚从学校出来的哪种激情也不在
3. 身体也越来越不行

国内这个焦虑确实蛮严重的，起码对我本人来说，一直存在。受限于学历的影响， 想做管理，也很难，爬又爬不上去。

下面就简单聊聊过去一年发生了什么

### 失业

我本人从未想过会被裁员，现在我也这么认为（当时的我不会被裁员），直到现实给我重拳出击。去年，B站大概有三波裁员潮，分别是年初，年中，年末。年中的时候，我组内有一位非常优秀的同学被裁了。哪会儿其实蛮慌的，生怕是自己。而且是在上海疫情期间。会经历裁员 + 疫情双重 Buffer 的叠加，很容易让人崩溃。

在上海疫情期间，我人已经在崩溃的边缘，我去过方舱，四月份阳的，在方舱待了一周左右的时间，真实体会过，什么叫人间疾苦。也压根不敢跟同事，家人，网上说，怕被歧视，哪会儿在小区的时候，就被居委会的人给歧视了。

年末，通知我被裁员。裁员的前几天，我领导跟我们组内的人都聊了聊，看谁能主动承担这个名额，领个大礼包。到我的时候，我当然是不愿意的，我有车贷，去年11月底提的车，所以很希望有一份稳定的工作，能够维持基本的生计。但是吧，裁员这事，一般是综合维度来考量，我复盘了一些衡量的点：

1. 刚入职（一年内
2. 跟领导的关系
3. 性价比
4. 可替代性（工作内容

大概以上这些，具体原因，直到现在我也不清楚，当时也想了解清楚具体原因，但都不说，也让我不要再问，ok，哪我也就不想再知道了

通知我被裁员的时候，我跟前端老板聊了蛮多的，当时我还跟天哥（敖天羽）聊了下（她内推我进来的）看是否能活水，转到她部门下，就不让活水，后面心态就放平了，哪就这样吧。技术总监过来找我的时候，言下之意，你肯定要走的，早走，早超生吧，大概这意思，对大家都好。其实他不找我，我也要走的，没有拖的意义，而且我个人觉得没必要浪费时间，再到后面HR过来找我的时候，我一轮谈判就同意了，不想跟他们再耗下去。

## 面试

在去年12月中旬被裁员之后，整个人就很 emo 的状态，做什么事都没有干劲，整天就是把自己锁在屋里，刷刷剧，打打游戏，饿了就叫外卖，简单的途径获取多巴胺和内啡肽，满足一天的基本需求。

现在回想起来，要是当时自驾从上海到新疆-西藏，整个人会舒服很多，又或者是专门开一个月的滴滴，体会下提前下岗再就业，这是我在最有闲的时间，没有去做的一些事，有点遗憾。希望后面可以补上，哈哈哈哈

12月下旬简单投了投简历，比如投了长沙腾讯云，想回老家看看机会，也收到了面试邀约，但由于本人心理没准备好，就拒绝了面试，想等到年后再面，年后再看就没机会了

躺平了12月份，1月份，过完年后，差不多到2月份了，再看机会，再投简历，很不幸，各大社区传来前端已死

#### 脉脉

![image](https://user-images.githubusercontent.com/16217324/229353100-f3fed57d-25a9-49d3-8db6-185c131678fb.png)

#### BOSS直聘

![image](https://user-images.githubusercontent.com/16217324/229352982-b18540d9-3857-4c61-aa54-8e9787602584.png)

#### 拉勾

![image](https://user-images.githubusercontent.com/16217324/229353058-4f426c10-5d0c-45f7-993f-6acc32c6d8c2.png)

![image](https://user-images.githubusercontent.com/16217324/229353160-3850d4f5-2360-40c7-9ec0-7643ae2c53ef.png)

很不幸，前端目前就是这么个现状，招聘软件上，基本都是已读不回，打招呼，没反应

我是这么看待前端已死的。先说结论，我本人是反对前端已死，理由大概如下：

#### 技术出海

最近几年，大厂的科技产品都在出海，寻石问路。抖音，拼多多，都做的不错，不再局限国内的人口红利，谋求更多的发展空间。同理，我们做技术的是否也可以寻找技术出海？我的答案是肯定的。国外项目平台有很多，比如 Upwork，在这个平台上，我们可以看到各个国家的机会，不会英语也没关系，借助翻译软件，简历包装等，寻求更多合作的机会，不要把自己局限住！

#### 核心竞争力

作为一名技术人，关键是创造自己的核心竞争力，什么叫核心竞争力，也就是你跟别人与众不同的地方，别人能做的，你能做。别人不能做的，你也能做，哪自然择优而优，这对所有公司来说都是这样，本质上就是花最小的代价，选择更合适的的人。举个简单的例子，我们以上面这份大厂JD（Job Describe）为例，基础部分就不讲了，关注几个指标：学历、工作经验、C端业务经验，加分项。通过这几个条件，可以筛选出一批人，如果你对加分项更加深入，哪你的优势很大

#### 人口红利

我们国内有个特点，哪个行业挣钱，哪个行业火，一堆人会进来（培训机构到处宣传），人口优势固然存在，这是一大优势，也是一大弱势。优势就不讲了。弱势就是会导致这个行业出奇的内卷。以互联网行业为例，早几年会个 ajax ，写个静态页面，专科以上学历，一堆人要。现在呢，你得懂源码、你得统招全日制学历以上、你得会多个技能，这都是基本的要求，哪如何找到差一点，比如熟练英语的读写，你又比一些人要优秀，机会更多，可以关注外企机会

#### 技术发展趋势

作为一名技术人，一定要关注前沿技术的发展趋势，为什么要关注？简单来说，这关乎你的生存空间。近几年 web3、区块链、元宇宙发展很快，如果你跟不上时代，很快就会被淘汰，很简单的道理。比如你看各大招聘软件上，各种 web3 的岗位，工资很高以及要求熟练英语读写

再说回来，2月份，3月份，基本盘，就没啥面试机会和合适的岗位。靠朋友内推，面试了几家，技术面到HR面聊完，就没啥消息。面试纯看缘分

2月底开始面的网易，网易是三轮技术面 + HR面，整个流程持续了大概20多天，在三月份的时候入职了，属实场景复刻。去年也差不多这个时间点面的网易严选，同样是三轮技术面 + HR面

### 未来

1. 博客改造升级
2. 组件库重构
3. 脚手架升级

持续关注前沿技术

也很庆幸自己是在30岁前经历了裁员，也让我更加坚定，互勉

### 总结

我其实是个非常不喜欢面试的人，面试这东西，个人觉得很看眼缘，我是一个很容易紧张的人，如果面试官不能给我有效的引导，我其实内心蛮慌的，这次能够有幸进入网易，真的很感谢老板，面试官 + 运气不错

文章更新平台：掘金、CSDN、知乎、思否、[博客](https://github.com/xuya227939/blog)

我的联系方式，v：Jiang9684，欢迎入群交流，和我沟通

完

**Comment by Kaier33** [comment]
至少,结局是好的.
共勉 ~

**Comment by kittors** [comment]
同97年，我也是个非常不喜欢面试的人，但是感觉公司快倒闭了，业务也越来越烂了，要准备跳槽了
