### ISSUE TITLE
入职网易是种什么体验

### ISSUE THREAD

**Issue by xuya227939** [xuya227939/blog#151]
已经入职网易一个多月了，能在今年这种行情下，还能入职，真的很幸运，而且我的第一学历还是专科，感谢努力的自己，简单聊聊B站和网易的入职体验吧！

### 入职初体验

网易，我入职的时候，只有我一个人！哈哈哈哈，"帝王般"的待遇，HR全程跟我一个人在培训，讲解重要内容，六险一金阿啥的

B站，可能由于是总部的原因，入职体验这方面，B站很好，我大概是在2022年3月份入职的B站，当时和HR约定的是周四入职（B站入职，一般是集中办理入职，周二和周四），当时大概和几百人一起入职，入职的第一天都是新人培训，重点事项都会讲到，实习生和社招有些福利上的区别，比如商业保险，社招有，实习无

### 食堂

网易，出了名的猪厂，食堂菜品丰富，而且随便拿，还有各种水果，牛奶尽情享受，把你全方位照顾好

B站，没有食堂，这点令我比较震惊，只有午餐15块饭补

![](https://files.mdnice.com/user/27515/21f65e89-04ad-40a3-aced-6448171fef61.jpg)

### 办公体验

网易，网易面试的时候，给我一种感觉，比较稳重，进来之后发现大家普遍工龄都很长，有好多人待了 5年、7年、8年、10年等等
每个人的工位都是用挡板拦起来，工位很大，有点类似国企，入职配备 mac 和 win 两台电脑以及双显示器，甚至是三显示器的都有

B站，B站整个公司氛围偏年轻化，而且女生真的很多！！！是我目前待过互联网公司，女性占比很高的一家公司，B站的办公椅和办公桌比较协调，办公起来非常舒服，而且最关键是能带宠物上班！！！很多同学会带猫阿，狗阿，上班，很温馨，上班累了，可以逗逗宠物，解解压，很舒缓，由于大家都偏年轻化，交流起来真的很方便，氛围比较好

![](https://files.mdnice.com/user/27515/b314bf40-64c6-4514-b843-62c05dfde75f.jpg)

### 社团

网易，我在的园区之前有社团，后面就无了。。。

B站，B站有各种各样的社团，基本上你不用担心你的爱好找不到队友

以上是比较简单的入职体验对比嘛，期待和大家沟通交流

文章同步更新平台：掘金、CSDN、知乎、思否、博客，公众号（野生程序猿江辰）
我的联系方式，v：Jiang9684，欢迎和我一起学习交流

完

**Comment by chinanoi** [comment]
大佬，那篇大厂面试题是你的面经吗，看你写的面试看起来都答得挺好的，为啥挂率那么高，是薪资要求比较高还是什么原因

**Comment by xuya227939** [comment]
大环境不行

chen ***@***.***> 于2023年7月7日周五 09:55写道：

**Comment by kittors** [comment]
大佬我和你同龄的，97年，双非本科，就职在一家小公司，前端入行2两年（之前干了两年的测试）。因为大环境确实不行，公司的业务也越来越烂了，自研项目不赚钱，开始接一堆外包项目。而且现在外包项目也没几个了，甲方单方面不干了，业务缩水严重。感觉公司快倒闭了，现在我已经重新梳理学习前端技术栈一个月了，而且极其焦虑。

**Comment by xuya227939** [comment]
@kittors  焦虑是正常的，找点事做，缓解下焦虑
